### Request to test orders api endpoint
GET http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json
Authorization: Basic Quint:quint
X-Requested-With: XMLHttpRequest

### Request to test orders api endpoint
GET http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json
Authorization: Basic Quint:quint
X-Requested-With: XMLHttpRequest

### Request to test Customers api endpoint
GET http://localhost:4004/odata/v4/catalog/Customers
Content-Type: application/json
Authorization: Basic Bob:bob
X-Requested-With: XMLHttpRequest

### Test restoreProductStocksBatch locally
POST http://localhost:4004/odata/v4/catalog/restoreProductStocksBatch
Content-Type: application/json
Authorization: Basic Quint:quint
X-Requested-With: XMLHttpRequest

{
  "ProductUpdates": [
    {"ProductName": "Set I", "QuantityToAdd": 1},
    {"ProductName": "Accessory G", "QuantityToAdd": 1}
  ]
}

### test updateInventoryAfterOrderPlacement action
POST http://localhost:4004/odata/v4/catalog/updateInventoryAfterOrderPlacement
Content-Type: application/json
Authorization: Basic Quint:quint
X-Requested-With: XMLHttpRequest

  {
    "productname": "Set I",
    "quantity": 1
  }

### Test Order Cancellation Request
POST http://localhost:4004/odata/v4/catalog/orderCancellationRequest
Content-Type: application/json
Authorization: Basic Quint:quint
X-Requested-With: XMLHttpRequest

{
  "orderId": "9acdc7e8-7c4b-4dfc-8dc6-527e3a124d93"
}

### test updateOrderStatus action
POST http://localhost:4004/odata/v4/catalog/updateOrderStatus
Content-Type: application/json
Authorization: Basic Quint:quint
X-Requested-With: XMLHttpRequest

{
  "orderId": "837f3b94-e5b3-4355-95e5-6b6e429b8c9a",
  "newStatus": "Returned",
  "comments": "Hello"
}

### test placeOrder action
POST http://localhost:4004/odata/v4/catalog/placeOrder
Content-Type: application/json
Authorization: Basic Quint:quint
X-Requested-With: XMLHttpRequest

{
    "input": {
        "customerId": "23987cc9-98ff-4226-b3da-b3142dbeb90b",
        "orderItems": [
            {
                "productId": "0e53cfe6-0a23-456c-888f-5f624573f92c",
                "quantity": 1
            },
            {
                "productId": "39e7e739-764e-46e8-8bcd-89de4f1a7e7e",
                "quantity": 1
            }
        ],
        "shipping": {
            "shipName": "John Doe",
            "shipAddress": "123 Main Street",
            "shipCity": "New York",
            "shipRegion": "NY",
            "shipPostalCode": "10001",
            "shipCountry": "USA"
        },
        "employeeId": 1,
        "orderDate": "2024-01-20",
        "freight": 25.50
    }
}
